/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maja_chaja_java_wroclaw;

import java.util.List;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        BasketSplitter splitter = new BasketSplitter("src/main/resources/config.json");
        List<String> basket = List.of("Cocoa Butter", "Tart - Raisin And Pecan", "Table Cloth 54x72 White", "Flower - Daisies", "Fond - Chocolate", "Cookies - Englishbay Wht");
        Map<String, List<String>> result = splitter.split(basket);
    }
}
