/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maja_chaja_java_wroclaw;

import java.util.List;
import java.util.Map;

public class App {
    public static void main(String[] args) {
        BasketSplitter splitter = new BasketSplitter("src/main/resources/config.json");
        List<String> basket = List.of("Fond - Chocolate", "Chocolate - Unsweetened", "Nut - Almond, Blanched, Whole", "Haggis", "Mushroom - Porcini Frozen", "Cake - Miini Cheesecake Cherry", "Sauce - Mint", "Longan", "Bag Clear 10 Lb", "Nantucket - Pomegranate Pear", "Puree - Strawberry", "Numi - Assorted Teas", "Apples - Spartan", "Garlic - Peeled", "Cabbage - Nappa", "Bagel - Whole White Sesame", "Tea - Apple Green Tea");
        Map<String, List<String>> result = splitter.split(basket);

        for (Map.Entry<String, List<String>> entry : result.entrySet()) {
            System.out.println("Delivery method: " + entry.getKey());
            System.out.println("Products: " + entry.getValue());
        }
    }
}
